# Generated by Django 2.2.2 on 2019-06-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
    ]
