# Generated by Django 2.2.2 on 2019-06-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_image_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image_link', models.CharField(blank=True, default=None, max_length=10000, null=True)),
            ],
        ),
    ]
