# Generated by Django 2.2.2 on 2019-06-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photographer',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
