# Generated by Django 2.2.2 on 2019-06-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190622_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='share_link',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
