# Generated by Django 2.2.2 on 2019-06-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_image_share_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
