# Generated by Django 2.2.2 on 2019-06-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_image_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
