# Generated by Django 2.2.2 on 2019-06-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_image_downloads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='download_url',
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_url',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
